### ISSUE TITLE
Usage in fragment

### ISSUE THREAD

**Issue by timbaev** [okaybroda/ImageZoom#1]
How I can override this method in fragment?
`@Override
public boolean dispatchTouchEvent(MotionEvent ev) {
    return imageZoomHelper.onDispatchTouchEvent(ev) || super.dispatchTouchEvent(ev);
}`

**Comment by okaybroda** [comment]
Just place that code in the Activity that holds that Fragment. The touch event should be passed down from the Activity to the Fragment's Views.
