### ISSUE TITLE
Great work, however there is a HUGE bug

### ISSUE THREAD

**Issue by kkawai-demo** [okaybroda/ImageZoom#2]
When you initially grab the image, there is a huge flicker!  I found this even on your sample app, so I know it's not anything I did when integrating into my project.

**Comment by okaybroda** [comment]
Fixed this issue in the 1.0.6 build by setting drawing cache to the placeholderView.

The flickering was happening due to Android's layout process after calls to addView and removeView.

**Comment by kkawai-demo** [comment]
Awesome fix! 

    On Tuesday, January 3, 2017 1:22 AM, Viventhraa Rao <notifications@github.com> wrote:
 

 Closed #2.—
