### ISSUE TITLE
zoom from touch coordinates not from center

### ISSUE THREAD

**Issue by jiteshrana** [okaybroda/ImageZoom#3]
Hello,
This is not a issue but I am trying to achieve the functionality like zooming image from its touch coordinates. can you help me through it ?
` updateZoomableViewMargins(newCenter[0] - twoPointCenter[0] + originalXY[0],
                        newCenter[1] - twoPointCenter[1] + originalXY[1]);`
I tried a lot to tweaking above code segment but couldn't get success.

**Comment by okaybroda** [comment]
If I understand what you mean, is it related to the pivot of the zoom? If you want it to be at the exact center of the image, the twoPointCenter variable should be set to midpoint of the view at the beginning of the zoom.

**Comment by jiteshrana** [comment]
Thanks for your reply. but, I need to zoom image (from pinch point) not from center. currently, it is zooming from center.

**Comment by jiteshrana** [comment]
Thank you for your hint. I have worked on it and after some code tweaking I got the result what i want in zooming image. Thanks once again.. 👍

**Comment by okaybroda** [comment]
Glad you got it. Would you mind making a contribution? It would help me and also anyone else using this project.

Cheers!

**Comment by jiteshrana** [comment]
Sure, would like to.. I have done so. Its not perfect but its similar to what i want.

Cheers!

**Comment by okaybroda** [comment]
Awesome! Could you send a pull request?

**Comment by jiteshrana** [comment]
Done.
