### ISSUE TITLE
Remove application element from the Manifest

### ISSUE THREAD

**Issue by lennynilsson** [okaybroda/ImageZoom#5]
The application element in the manifest causes merge failures when the library is used in an application with allowBackup="true".

https://github.com/okaybroda/ImageZoom/blob/master/library/src/main/AndroidManifest.xml

It is possible to override with 'tools:replace="android:allowBackup", but it would be nice if the property can be used as intended.

**Comment by okaybroda** [comment]
Removed allowBackup and supportsRtl attributes.

Cheers!
