### ISSUE TITLE
After release one finger I have a graphic bug

### ISSUE THREAD

**Issue by retuner87** [okaybroda/ImageZoom#7]
Hi, some compliments for the lib, it is the most powerful pinch to zoom that exist 👍 
But I have a problem after release one finger: the view is moved down.

Here the xml: https://www.dropbox.com/s/qhy607wi45rb803/activity.xml?dl=0
Here the view before zoom: https://www.dropbox.com/s/mfe0ocijvrolggi/1.png?dl=0
Here the view after release one finger from zoom: https://www.dropbox.com/s/4am83s6tnonnqko/2.png?dl=0

I've colored view to know which is moved.

Can you help me?

Thanks!

**Comment by okaybroda** [comment]
Hi @retuner87 , there has always been a lingering bug in the library which was hard to find and debug. Thanks for pointing out I'll get back with a solution as soon as possible.

Cheers and thanks!

**Comment by developerhuman12** [comment]
I am having the same issue as @retuner87 . For testing I have created this layout:
`<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">


    
        
        
        
        

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ImageView
            android:id="@+id/photo_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:src="@drawable/nissan_car"/>
    </FrameLayout>


</RelativeLayout>`
And when I release my view after pinch zoom then my car image shifted to bottom  of layout.
Can @okaybroda help

**Comment by okaybroda** [comment]
Fixed.

**Comment by retuner87** [comment]
Thanks @okaybroda ; how can I pull the fix and test it on my application?
